---
kind: pipeline
name: default

steps:
  - name: composer
    image: composer:2.0.11
    commands:
      - composer install

  - name: phpstan
    image: php:8.0-alpine
    commands:
      - ./vendor/bin/phpstan analyze src/ --level=max
    depends_on:
      - composer

  - name: php-cs-fixer
    image: php:8.0-alpine
    commands:
      - ./vendor/bin/php-cs-fixer fix --dry-run --diff src/
    depends_on:
      - composer

  - name: codeception
    # For now we use this relatively unpopular image because it has PHP 7.3 and XDEBUG
    image: timfennis/pcov
    commands:
      - ./vendor/bin/codecept run unit --coverage-xml
    depends_on:
      - composer

  - name: upload coverage
    image: plugins/codecov
    settings:
      token: '1c185a5a-f857-4eee-a767-7050032363d7'
      files:
        - '*.xml'
      paths:
        - 'tests/_output'
    depends_on:
      - codeception


